# Generated by Django 4.0.4 on 2022-06-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_class_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cdeptno',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='cmax_number',
            field=models.IntegerField(null=True, verbose_name='课程最大人数'),
        ),
        migrations.AlterField(
            model_name='course',
            name='cno',
            field=models.AutoField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
