# Generated by Django 4.0.4 on 2022-06-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_course_cdeptno_course_cmax_number_alter_course_cno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cno',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
