# Generated by Django 4.0.4 on 2022-06-22 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_course_cno'),
    ]

    operations = [
        migrations.CreateModel(
            name='SC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=1)),
                ('cno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.course')),
                ('sno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.student')),
            ],
        ),
    ]
